{% set name = "dbt-bigquery" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_bigquery-{{ version }}.tar.gz
  sha256: 3dc27fd43bf198fac58445c73b500513eaf24b523b344b67a935d0fa211c0133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - google-cloud-aiplatform >=1.72.0
    - nbformat >=5.10.4
    - python >={{ python_min }}
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.7,<2.0
    - google-cloud-bigquery-core >=3.0,<4.0
    - google-cloud-storage >=2.4,<3.2
    - google-cloud-dataproc >=5.0,<6.dev0
    - google-api-core >=2.11.0
    - dbt-core >=1.8.0

test:
  imports:
    - dbt.adapters.bigquery
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-bigquery
  summary: The BigQuery adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
