{% set name = "dbt-bigquery" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0468057e91dd75a75c41d3b468685cb2cd9340b2e9770805cda65613f95bfe01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.7,<2.0
    - google-cloud-bigquery-core >=3.0,<4.0
    - google-cloud-storage >=2.4,<3.dev0
    - google-cloud-dataproc >=5.0,<6.dev0
    - google-api-core >=2.11.0
    - dbt-core >=1.8.0

    # from google-cloud-bigquery[pandas]
    - pandas >=1.1.0
    - pyarrow >=3.0.0
    - db-dtypes >=0.3.0,<2.0.0dev

test:
  imports:
    - dbt.adapters.bigquery
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dbt-labs/dbt-bigquery
  summary: The BigQuery adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
