{% set name = "dbt-bigquery" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-bigquery-{{ version }}.tar.gz
  sha256: 610c1a895ff25890f01887f36556dbb3ff2027bf1f02587097665efe99c5565a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    # via Grayskull
    - google-api-core >=2.11.0
    - python >=3.8
    - dbt-core >=1.7.0,<1.8.dev0
    - google-cloud-bigquery-core >=3.0,<4.dev0
    - google-cloud-storage >=2.4,<3.dev0
    - google-cloud-dataproc >=5.0,<6.dev0

test:
  imports:
    - dbt.adapters.bigquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-bigquery
  summary: The BigQuery adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - maresb
    - thewchan
