schema_version: 1

context:
  name: dbt-bigquery
  version: "1.12.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 71787ff4495999a26058dffe4da46558acf57bdc409cdb46565d9afb0391c75e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.24.4,<2.0
    - google-cloud-bigquery-core >=3.0,<4.0
    - google-cloud-storage >=2.4,<3.2
    - google-cloud-dataproc >=5.0,<6.dev0
    - google-api-core >=2.11.0
    - google-auth >=2.29.0
    - dbt-core >=1.10.0rc0,<2.0
    - nbformat >=5.10.4
    - google-cloud-aiplatform >=1.148.0

tests:
  - python:
      imports:
        - dbt.adapters.bigquery
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The BigQuery adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/dbt-labs/dbt-bigquery

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
